### ISSUE TITLE
NuGet Installation fails

### ISSUE THREAD

**Issue by Gino** [Akaion/Bleak#15]
Hi there,

I am currently experiencing the following error as soon as I want to install Bleak by using NuGet into a normal C# (Windows Forms) project.

`Could not install package 'Bleak 2.7.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Not really sure how I can fix this issue, also quite new to C# and Visual Studio.
Hope someone could help me out with this.

Thanks.

**Comment by Akaion** [comment]
Latest version dropped support for .Net Framework due to .Net Standard not having the API's I needed to use.

You have a few options here

- Use an older version of the library (I believe 2.6 versions should work fine)
- Swap to .Net core (you should be fine using the beta version of .Net core 3 as I assume this is for personal use)
- Wait until .Net core 3 is officially released and then create your winforms using that and use my library alongside it (I will be updating the library to .Net core 3 the day of release.)
