### ISSUE TITLE
Exception when injecting a embedded resource.

### ISSUE THREAD

**Issue by TheGreyRaven** [Akaion/Bleak#19]
I _might_ have found an issue.
If I try to inject an embedded DLL resouce the program will crash with the exception FileNotFound (System.Runtime).
This is the code I used:
```
var injector = new Injector(target.Id, Properties.Resources.DLL, InjectionMethod.ManualMap, InjectionFlags.None);
injector.InjectDll();
```
Also a second issue:
If I create a new Net Framework project and try to add Bleak using NuGet I get this error:
```
Could not install package 'Bleak 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				
```

**Comment by Akaion** [comment]
I'll have a look into the embedded DLL issue later today, I can't say I know what the problem is off the top of my head.

Regarding the second, issue, 3.0 is written in .Net Core and will not work in Framework currently. When .Net Standard 2.1 drops I will probably change it back to that if it has the API's that I need, however, going forward I will probably end up using API's that are exclusive to .Net Core 3.0+ which will mean you will need to make to the swap to .Net Core 3. There shouldn't be any reason why you can't do this as WinForms/Wpf support is comming .Net Core 3.

**Comment by Akaion** [comment]
@TheGreyRaven it may be worth retrying with 3.0.1, there was a small bug with parsing the DebugDirectories that would have been needed for manual mapping, which I fixed.

**Comment by TheGreyRaven** [comment]
The issue seems to be resolved now, thank you!
