### ISSUE TITLE
Add support for Byte Array injection from remote address!

### ISSUE THREAD

**Issue by TheGreyRaven** [Akaion/Bleak#2]
We spoke a bit on Discord about Byte Array injection from a remote address.
I was thinking that instead of having the dll stored on the users hard-driver you could use a function like this:
```
    private static byte[] DownloadFile(string url)
    {
        byte[] result = null;

        using (WebClient webClient = new WebClient())
        {
            result = webClient.DownloadData(url);
        }

        return result;
    }
```
In order to download the file directly into the programs memory as a Byte Array and then inject using that Array we just downloaded.

So that we in the end could do something like this (or similar):
```
injector.CreateRemoteThread("processName", DownloadFile("http://127.0.0.1:8080/path/to/thedll.dll"));
```

**Comment by Akaion** [comment]
We need to discuss this a bit as it is a rather broad question with some limitations.

I think the best way to do this would be to implement a feature where you provide a byte[] of the DLL bytes instead of a string to a DLL path, that way you can implement your own solutions to getting files from webservers.

Now the problem arises with injecting the byte array.  There are 2 solutions to this. 

The first involves converting the byte array to a temporary DLL file for a few milliseconds and then deleting it after the injection has occurred. If this was the method I was to use then all the injection methods & extension methods could be used but you would be writing to disk (deleting after though)

The second would require no writing to disk and directly using a byte array, however, the only way this would work would be by using manual mapping (as you cannot pass a byte[] to load library). 

I'm more inclined to use the first solution as the second solution kind of defeats the purpose of having this library and you will not be able to use any of the features bar manual mapping.

Let me know what you think @TheGreyRaven

**Comment by TheGreyRaven** [comment]
The first solution sounds best and simplest so think it's best to go on that one!

**Comment by Akaion** [comment]
You're request has been implemented :))

**Comment by mfaerevaag** [comment]
Sorry to bump an old issue, but I'd also love to discuss this. Saw direct mapping is listed as a feature, though it seems that you went for writing the DLL to disk and injection it? Also on Discord if you're willing to discuss 👍

**Comment by Akaion** [comment]
@mfaerevaag Could you open a new issue outlining this. Definitely possible with manual mapping
